apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
data:
  DRONE_GITHUB_CLIENT_ID: 3a5bb3d041634decbddd #Get this from GitHub OAUTH
  DRONE_GITHUB_CLIENT_SECRET: ce51729c82d8eae33e6fd70ee209fb366e06b10e #Get this from GitHub OAUTH
  DRONE_RPC_SECRET: 6ddb82f167530f281c863e6100103c45 #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: cG9zdGdyZXM6Ly9wb3N0Z3Jlc2FkbWluOmFkbWluMTIzQDEwLjQzLjE5Mi43OjU0MzIvcG9zdGdyZXNkYj9zc2xtb2RlPWRpc2FibGUK
  DRONE_USER_CREATE: dXNlcm5hbWU6U3VsZWtoYTAyMTEyMDAxLGFkbWluOnRydWUK
  DRONE_SERVER_HOST: ZWMyLTEzLTIzNS0xMzUtMjUyLmFwLXNvdXRoLTEuY29tcHV0ZS5hbWF6b25hd3MuY29tCg== #drone.marceldempers.dev
