apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  labels:
    app: drone-server
  annotations:
spec:
  selector:
    matchLabels:
      app: drone-server
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        - name: drone-server
          image: drone/drone:1.6.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 30385
            - containerPort: 31864
          env:
            - name: DRONE_USER_CREATE
              value: username:Sulekha02112001,admin:true
            - name: DRONE_DATABASE_DRIVER
              value: postgres
            - name: DRONE_DATABASE_DATASOURCE
              value: postgres://postgresadmin:admin123@10.43.192.7:5432/postgresdb?sslmode=disable
            - name: DRONE_SERVER_PROTO
              value: http
            - name: DRONE_SERVER_HOST
              value: 13.235.135.252
            - name: DRONE_GITHUB_CLIENT_ID
              value: 3a5bb3d041634decbddd
            - name: DRONE_GITHUB_CLIENT_SECRET
              value: ce51729c82d8eae33e6fd70ee209fb366e06b10e
            - name: DRONE_RPC_SECRET
              value: 6ddb82f167530f281c863e6100103c45
